env:
  browser: true
  es2021: true
extends: plugin:react/all
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'react'
rules: {}
