name: Publish

on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 8.15.3
        - uses: actions/setup-node@v3
          with:
            node-version: 21.x
            cache: "pnpm"

        - run: pnpm install --frozen-lockfile
        - run: pnpm build
        - run: pnpm publish
